name: "gcloud auth"

description: "Authenticate to Google cloud"

branding:
  icon: "log-in"
  color: "green"

runs:
  using: "composite"
  steps:
    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v1"
      with:
        workload_identity_provider: "projects/336371362626/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
        service_account: "github-actions@zones-cloud.iam.gserviceaccount.com"
        create_credentials_file: true
