apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: redis
value: 1000002
globalDefault: false
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: redis-l1
value: 1000001
globalDefault: false
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: redis-l2
value: 1000001
globalDefault: false
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: redis-replica
value: 1000000
globalDefault: false
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: redis-other
value: 100002
globalDefault: false
