apiVersion: v1
kind: Service
metadata:
  name: prometheus-ui
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "biomes-internal"}'
spec:
  clusterIP: None
  selector:
    app: prometheus-ui
  ports:
    - name: http
      port: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-ui
  template:
    metadata:
      labels:
        app: prometheus-ui
      namespace: default
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/proxy-await: enabled
        config.linkerd.io/skip-subnets: 169.254.169.254/32
    spec:
      serviceAccountName: zones-backend
      containers:
        - name: frontend
          image: "gke.gcr.io/prometheus-engine/frontend:v0.5.0-gke.0"
          args:
            - "--web.listen-address=:9090"
            - "--query.project-id=zones-cloud"
          ports:
            - name: http
              containerPort: 9090
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
