# See:
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
# This is for making the checks always exist, even if the path filter doesn't match.

name: ts-eslint-ci

on:
  pull_request:
    paths-ignore:
      - "src/**"

jobs:
  ts-ci:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No TS-ESLint CI required"'
